### ISSUE TITLE
Running a Bespoke Command

### ISSUE THREAD

**Issue by EventReplay** [bitfocus/companion-module-extron-dxp#3]
I obvious didn't quite understand how the run command works from the dcs module which is why it didn't make the commit?

I wanted to be able to input a known command string and send straight to the matrix. This can be used to send multiple commands at the same time.

Any advice would be apreciated.

Many Thanks.

**Comment by JeffreyDavidsz** [comment]
@EventReplay if you are talking about the custom option, on purpose we leave it out. We want users to request options so everyone can benefit from it. In this module it would give it the option to have a generic telnet module, which we don't want for now. I understand your question. Does the string always have a starting prefix? When you build that in, the "open/custom option" is no problem as this is then only usable for the matrix
