### ISSUE TITLE
Missing self.

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion-module-extron-dxp#7]
https://github.com/bitfocus/companion-module-extron-dxp/blob/c4bb92cfdbc286f69de45691f1b3f21b5ff7ad67/index.js#L124

This line, and also line 129 is missing "self." in front of socket.write

**Comment by EventReplay** [comment]
This is on my radar after seeing the commit from @JeffreyDavidsz on SMP351

**Comment by EventReplay** [comment]
@haakonnessjoen @JeffreyDavidsz I've made changes & submitted a pull request.

I'm not sure what I've done re branches sorry, I'm still stumbing around github!

**Comment by JeffreyDavidsz** [comment]
I think you are ok :-)
